import { MediaRules } from "./types";

export const mediaTypes: MediaRules = {
  images: [
    "jpg",
    "jpeg",
    "png",
    "gif",
    "webp",
    "bmp",
    "tiff",
    "svg",
    "ico",
    "heic",
    "avif",
  ],
  videos: [
    "mp4",
    "mov",
    "avi",
    "mkv",
    "flv",
    "wmv",
    "webm",
    "mpeg",
    "3gp",
    "m4v",
  ],
  audio: ["mp3", "wav", "aac", "flac", "ogg", "m4a", "wma", "amr", "aiff"],
  documents: [
    "pdf",
    "doc",
    "docx",
    "xls",
    "xlsx",
    "ppt",
    "pptx",
    "txt",
    "rtf",
    "odt",
    "ods",
    "odp",
  ],
  archives: ["zip", "rar", "7z", "tar", "gz", "bz2", "xz"],
  code: [
    "js",
    "ts",
    "jsx",
    "tsx",
    "html",
    "css",
    "scss",
    "json",
    "xml",
    "py",
    "java",
    "c",
    "cpp",
    "cs",
    "php",
    "rb",
  ],
  fonts: ["ttf", "otf", "woff", "woff2", "eot"],
  executables: ["exe"],
  androidApps: ["apk"],
  binaries: ["bin"],
  diskImages: ["iso"],
  installer: ["dmg", "msi"],
  spreadsheets: ["csv"],
  markdown: ["md"],
  logs: ["log"],

  // others: [], --> Auto added in plan builder
};
